languageCode = "en"
languageName = "English"
weight = 1
title = "Cyberls-Blog"

[params]
author = { name = "Cyberl-ty02", image = "wxt01.jpg" }
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "wxt01.jpg"
secondaryLogo = "wxt01.jpg"
description = ""


