# baseURL = 'https://cyberl-ty02.github.io/'
baseURL = 'https://hatsunemiku.club/'

# 如果你的博客主要语言是中文的话, 需要将其设置为
languageCode = 'zh-CN'
defaultContentLanguage = "zh-CN"

title = 'My Own Blog'

[Params]
  [Params.footer]
    showCopyright = true
    copyright = "&copy; {{ now.Format \"2006\" }} Cyberl-ty02. This work is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/)."
